/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaDatos.ClsConecxion;
import java.io.File;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fundamentos DS
 */
public class WinAgenda extends javax.swing.JFrame {
    ClsConecxion base;
    String nombre,telefono,celular,Base,buscar;
    int clvCont;
    /**
     * Creates new form WinAgenda
     */
    public WinAgenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Archivo.setVisible(false);
        this.PanelAgenda.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtFijo = new javax.swing.JTextField();
        BtnInsertar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaContactos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnBuscar = new javax.swing.JButton();
        TxtBuscar = new javax.swing.JTextField();
        TxtCelular1 = new javax.swing.JTextField();
        Archivo = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuConectar = new javax.swing.JMenu();
        MnuAgenda = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAgenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Agenda");
        PanelAgenda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        PanelAgenda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Celular:");
        PanelAgenda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Telefono Fijo:");
        PanelAgenda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        PanelAgenda.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));
        PanelAgenda.add(TxtFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, -1));

        BtnInsertar.setText("Insertar Contactos");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });
        PanelAgenda.add(BtnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 53, -1, -1));

        BtnModificar.setText("Modificar Contacto");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        PanelAgenda.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 83, -1, 20));

        BtnEliminar.setText("Eliminar Contacto");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        PanelAgenda.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 113, 123, 20));

        TablaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Telefono Fijo", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaContactos);

        PanelAgenda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 100));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        PanelAgenda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBuscar.setText("Buscar Contacto");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));
        jPanel1.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        PanelAgenda.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 200, 70));
        PanelAgenda.add(TxtCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, -1));

        getContentPane().add(PanelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 370));

        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(Archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 510, 350));

        MnuConectar.setText("Conectar Base");
        MnuConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuConectarActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnuConectar);

        MnuAgenda.setText("Agenda");
        MnuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAgendaActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnuAgenda);

        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        nombre=TxtNombre.getText();
        telefono=TxtFijo.getText();
        celular=TxtFijo.getText();
        try{
           base.insetar("Agenda", nombre, telefono, celular);
           TxtNombre.setText("");
           TxtFijo.setText("");
           TxtBuscar.setText("");
           jLabel5.setEnabled(true);
           jLabel5.setText("Ingreso Correcto");
           TxtNombre.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            DefaultTableModel model= new DefaultTableModel();
            TablaContactos.setModel(model);
            base.mostrartabla("Agenda");
            ResultSetMetaData rsmd =base.registros().getMetaData();
            int columnas= rsmd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Telefono Fijo");
            model.addColumn("Celular");
            while(base.registros().next()){
                Object [] filas= new Object[columnas];
                for (int i=0;i<columnas;i++){
                    filas[i]=base.registros().getObject(i+1);
                }
                model.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        buscar=TxtBuscar.getText();
        try{
            base.busqueda("Agenda", buscar);
            jLabel5.setEnabled(true);
            jLabel5.setText("Busqueda Finalizada");
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            DefaultTableModel model= new DefaultTableModel();
            TablaContactos.setModel(model);
            base.mostrartabla("Agenda");
            ResultSetMetaData rsmd =base.registros().getMetaData();
            int columnas= rsmd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Telefono Fijo");
            model.addColumn("Celular");
            while(base.registros().next()){
                Object [] filas= new Object[columnas];
                for (int i=0;i<columnas;i++){
                    filas[i]=base.registros().getObject(i+1);
                }
                model.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void MnuConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuConectarActionPerformed
       this.Archivo.setVisible(true);
    }//GEN-LAST:event_MnuConectarActionPerformed

    private void MnuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAgendaActionPerformed
        this.PanelAgenda.setVisible(true);
        this.jLabel5.setEnabled(false);
        try{
            DefaultTableModel model= new DefaultTableModel();
            TablaContactos.setModel(model);
            base.mostrartabla("Agenda");
            ResultSetMetaData rsmd =base.registros().getMetaData();
            int columnas= rsmd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Telefono Fijo");
            model.addColumn("Celular");
            while(base.registros().next()){
                Object [] filas= new Object[columnas];
                for (int i=0;i<columnas;i++){
                    filas[i]=base.registros().getObject(i+1);
                }
                model.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuAgendaActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        File f=Archivo.getSelectedFile();
        Base=f.getAbsolutePath();
        Archivo.setVisible(false);
        base=new ClsConecxion(Base);
    }//GEN-LAST:event_ArchivoActionPerformed

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        nombre=TxtNombre.getText();
        telefono=TxtFijo.getText();
        celular=TxtFijo.getText();
        try{
            base.actualizarC("Agenda", nombre, telefono, celular, clvCont);
            TxtNombre.setText("");
            TxtFijo.setText("");
            TxtBuscar.setText("");
            jLabel5.setEnabled(true);
            jLabel5.setText("Ingreso Correcto");
            TxtNombre.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            DefaultTableModel model= new DefaultTableModel();
            TablaContactos.setModel(model);
            base.mostrartabla("Agenda");
            ResultSetMetaData rsmd =base.registros().getMetaData();
            int columnas= rsmd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Telefono Fijo");
            model.addColumn("Celular");
            while(base.registros().next()){
                Object [] filas= new Object[columnas];
                for (int i=0;i<columnas;i++){
                    filas[i]=base.registros().getObject(i+1);
                }
                model.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        try {
            base.eliminarC("Agenda", clvCont);
            
        } catch (SQLException ex) {
            Logger.getLogger(WinAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Archivo;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JMenu MnuAgenda;
    private javax.swing.JMenu MnuConectar;
    private javax.swing.JMenu MnuSalir;
    private javax.swing.JPanel PanelAgenda;
    private javax.swing.JTable TablaContactos;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtCelular1;
    private javax.swing.JTextField TxtFijo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
